actuators/universal_robots: went back to using io-publish in the test
version of nc installed on the test server does not work as intended (there is no socat there either), so the test uses io-publish.
ur-arm test is disabled until the necessary changes on the test server that make io-publish available there for snark.
pkill is used in the test to kill all created background processes cleanly ( while, sleep, io-publish).
option -4 is added to nc calls in ur-arm get and send functions for compatibility with the nc version installed on the test server.

diff --git a/actuators/universal_robots/test/ur-arm/test b/actuators/universal_robots/test/ur-arm/test
--- a/actuators/universal_robots/test/ur-arm/test
+++ b/actuators/universal_robots/test/ur-arm/test
@@ -9,20 +9,26 @@ status_sample=status_sample_stationary.bin
 real_target=$( cat $status_sample | ur-arm-status --fields=arm/angles )
 fake_target=1,2,3,4,5,6
 
-function port_is_used { lsof -n -i tcp:$publisher_port | wc -l; }
-function publish { cat $1 | nc -l $publisher_port; }
+if (( `lsof -n -i tcp:$publisher_port | grep LISTEN | wc -l` )); then 
+    echo "$( readlink -f `basename $0` ): required port $publisher_port is already in use, try changing publisher port in config.json" >&2
+    exit 1
+fi
 
-if (( `port_is_used` )); then echo "$( readlink -f `basename $0` ): required port $publisher_port is already used, try changing publisher port in config.json" >&2; exit 1; fi
-ur-arm wait --target=$fake_target --config=$config --prefix=$prefix --timeout=$timeout --tolerance=$angle_tolerance
+./ur-arm wait --target=$fake_target --config=$config --prefix=$prefix --timeout=$timeout --tolerance=$angle_tolerance
 status=$?
 echo "waypoint/no_publisher/status=$status"
 
-publish $status_sample & while (( ! `port_is_used` )); do :; done
-ur-arm wait --target=$fake_target --config=$config --prefix=$prefix --timeout=$timeout --tolerance=$angle_tolerance
+function bye { pkill -P $$; }
+trap 'bye' INT HUP TERM 
+
+while :; do cat $status_sample; sleep 0.01; done | io-publish -s $( ur-arm-status --packet-size ) tcp:$publisher_port 2>/dev/null &
+./ur-arm wait --target=$fake_target --config=$config --prefix=$prefix --timeout=$timeout --tolerance=$angle_tolerance
 status=$?
 echo "waypoint/timed_out/status=$status"
+pkill -P $$
 
-publish $status_sample & while (( ! `port_is_used` )); do :; done
-ur-arm wait --target=$real_target --config=$config --prefix=$prefix --timeout=$timeout --tolerance=$angle_tolerance
+while :; do cat $status_sample; sleep 0.01; done | io-publish -s $( ur-arm-status --packet-size ) tcp:$publisher_port 2>/dev/null &
+./ur-arm wait --target=$real_target --config=$config --prefix=$prefix --timeout=$timeout --tolerance=$angle_tolerance
 status=$?
 echo "waypoint/success/status=$status"
+pkill -P $$
