actuators/universal_robots: got rid of -d option in call for nc and switched to using lsof in ur-arm test

diff --git a/actuators/universal_robots/test/ur-arm/test b/actuators/universal_robots/test/ur-arm/test
--- a/actuators/universal_robots/test/ur-arm/test
+++ b/actuators/universal_robots/test/ur-arm/test
@@ -7,7 +7,11 @@ timeout=0.1
 angle_tolerance=0.0001
 status_sample=status_sample_stationary.bin
 
-nc -z localhost $publisher_port && { echo "$( readlink -f `basename $0` ): required port $publisher_port is already in use, try changing publisher port in config.json" >&2; exit 1; }
+if (( `lsof -n -i tcp:$publisher_port | grep LISTEN | wc -l` )); then 
+    echo "$( readlink -f `basename $0` ): required port $publisher_port is already in use, try changing publisher port in config.json" >&2
+    exit 1
+fi
+
 ur-arm wait --target=1,2,3,4,5,6 --config=$config --prefix=$prefix --timeout=$timeout --tolerance=$angle_tolerance
 status=$?
 echo "waypoint/no_publisher/status=$status"
