jai-generate-ld-conf: a quick and dirty libtiff symlinking implemented

diff --git a/sensors/cameras/jai/jai-generate-ld-conf b/sensors/cameras/jai/jai-generate-ld-conf
--- a/sensors/cameras/jai/jai-generate-ld-conf
+++ b/sensors/cameras/jai/jai-generate-ld-conf
@@ -4,12 +4,17 @@ echo "jai-generate-ld-conf: generating $( pwd )/jai.conf..." >&2
 echo "jai-generate-ld-conf: genicam lib dir: $1" >&2
 if [[ -n "$( uname -a | grep i686 )" ]] ; then
     lib=lib
-    genicam_lib=Linux32_i86
 else
     lib=lib64
-    genicam_lib=Linux64_x64
+fi
+# hyper quick and dirty; it sucks big time, but read jai user's guide for linux installation
+libtiff_3=$( locate libtiff.so | grep "/usr" | grep "libtiff.3.so$" )
+if [[ -z "$libtiff_3" ]] ; then
+    libtiff=$( locate libtiff.so | grep "/usr" | grep "libtiff.so$" )
+    [[ -n "$libtiff" ]] || { echo "jai-generate-ld-conf: failed to find libtiff.so" ; exit 1 ; }
+    ln -s $libtiff $1/libtiff.so.3
 fi
 echo "/usr/$lib" > jai.conf
-echo "/usr/local/$lib" > jai.conf
-echo "$1" > jai.conf
+echo "/usr/local/$lib" >> jai.conf
+echo "$1" >> jai.conf
 echo "jai-generate-ld-conf: generated $( pwd )/jai.conf" >&2
