points-from-ros/test: source ros setup file
it appears to be necessary for melodic

diff --git a/ros/applications/test/points-from-ros/test b/ros/applications/test/points-from-ros/test
--- a/ros/applications/test/points-from-ros/test
+++ b/ros/applications/test/points-from-ros/test
@@ -1,7 +1,12 @@
 #!/bin/bash
 
-source $( type -p comma-test-util ) || { echo "$0: failed to source comma-test-util" >&2 ; exit 1 ; }
+scriptname=$( basename $0 )
+source $( type -p comma-test-util ) || { echo "$scriptname: failed to source comma-test-util" >&2 ; exit 1 ; }
 
-export ROS_MASTER_URI=http://localhost:11311
+for distro in noetic melodic kinetic; do
+    setup_script=/opt/ros/$distro/setup.bash
+    [[ -f $setup_script ]] && source $setup_script && break
+done
+[[ -f $setup_script ]] || { echo "$scriptname: couldn't source ros setup.bash script" >&2; exit 1; }
 
 comma_test_commands
