actuators/universal_robots/applications/ur-arm: made exit codes due to config errors more consistent

diff --git a/actuators/universal_robots/applications/ur-arm b/actuators/universal_robots/applications/ur-arm
--- a/actuators/universal_robots/applications/ur-arm
+++ b/actuators/universal_robots/applications/ur-arm
@@ -188,8 +188,8 @@ function select_target_and_wait
 {
     local -r angles="$options_angles"
     local -r pose="$options_pose"
-    if [[ -n "$angles" && -n "$pose" ]]; then echo "$name: $FUNCNAME: options --angles and --pose are mutually exclusive" >&2; exit 1; fi
-    if [[ -z "$angles" && -z "$pose" ]]; then echo "$name: $FUNCNAME: target is not given, use --angles or --pose to specify the target" >&2; exit 1; fi
+    if [[ -n "$angles" && -n "$pose" ]]; then echo "$name: $FUNCNAME: options --angles and --pose are mutually exclusive" >&2; exit -1; fi
+    if [[ -z "$angles" && -z "$pose" ]]; then echo "$name: $FUNCNAME: target is not given, use --angles or --pose to specify the target" >&2; exit -1; fi
     if [[ -n "$angles" ]]; then wait_for_target "arm/angles" "$angles" $number_of_joints $options_timeout; exit $?; fi
     if [[ -n "$pose" ]]; then wait_for_target "tool/pose" "$pose" $number_of_pose_fields $options_timeout; exit $?; fi
 }
@@ -202,7 +202,7 @@ function wait_for_mode
     while [[ "$( get 'mode' )" != "$expected_mode" || "$( get 'arm/modes' )" != "$expected_joint_modes" ]]; do
         sleep 0.1
         if [[ -z "$end_time" ]]; then continue; fi
-        if (( `echo "$( time_ ) > $end_time" | bc -l` )); then echo "$name: $FUNCNAME: timed out waiting for mode $expected_mode and joint modes $expected_joint_modes" >&2; exit 1; fi
+        if (( `echo "$( time_ ) > $end_time" | bc -l` )); then echo "$name: $FUNCNAME: timed out waiting for mode $expected_mode and joint modes $expected_joint_modes" >&2; exit -1; fi
     done
 }
 
@@ -213,18 +213,18 @@ function turn_on
     local -r mode_init=$( ur-arm-status --mode-from-name initialising )
     local -r joint_mode_idle=$( ur-arm-status --joint-mode-from-name idle )
     local -r joint_mode_init=$( ur-arm-status --joint-mode-from-name initialisation )
-    if [[ -z "$mode_no_power" ]]; then echo "$name: $FUNCNAME: no-power mode undefined, check if 'ur-arm-status --mode-from-name no-power' works" >&2; exit 1; fi
-    if [[ -z "$mode_stop" ]]; then echo "$name: $FUNCNAME: stop mode undefined, check if 'ur-arm-status --mode-from-name security-stopped' works" >&2; exit 1; fi
-    if [[ -z "$mode_init" ]]; then echo "$name: $FUNCNAME: init mode undefined, check if 'ur-arm-status --mode-from-name initialising' works" >&2; exit 1; fi
-    if [[ -z "$joint_mode_idle" ]]; then echo "$name: $FUNCNAME: joint idle mode undefined, check if 'ur-arm-status --joint-mode-from-name idle' works" >&2; exit 1; fi
-    if [[ -z "$joint_mode_init" ]]; then echo "$name: $FUNCNAME: joint initialisation mode undefined, check if 'ur-arm-status --joint-mode-from-name initialisation' works" >&2; exit 1; fi
+    if [[ -z "$mode_no_power" ]]; then echo "$name: $FUNCNAME: no-power mode undefined, check if 'ur-arm-status --mode-from-name no-power' works" >&2; exit -1; fi
+    if [[ -z "$mode_stop" ]]; then echo "$name: $FUNCNAME: stop mode undefined, check if 'ur-arm-status --mode-from-name security-stopped' works" >&2; exit -1; fi
+    if [[ -z "$mode_init" ]]; then echo "$name: $FUNCNAME: init mode undefined, check if 'ur-arm-status --mode-from-name initialising' works" >&2; exit -1; fi
+    if [[ -z "$joint_mode_idle" ]]; then echo "$name: $FUNCNAME: joint idle mode undefined, check if 'ur-arm-status --joint-mode-from-name idle' works" >&2; exit -1; fi
+    if [[ -z "$joint_mode_init" ]]; then echo "$name: $FUNCNAME: joint initialisation mode undefined, check if 'ur-arm-status --joint-mode-from-name initialisation' works" >&2; exit -1; fi
     local mode="$( get 'mode' )"
-    if [[ -z "$mode" ]]; then echo "$name: $FUNCNAME: failed to get mode, check if status daemon is publishing on port $publisher_port" >&2; exit 1; fi
-    if [[ "$mode" != "$mode_no_power" ]]; then echo "$name: $FUNCNAME: expected the arm to be in mode $mode_no_power (no-power), got mode $mode" >&2; exit 1; fi
-    if [[ $( get 'arm/modes' | tr ',' '\n' | wc -l ) != $number_of_joints ]]; then echo "$name: $FUNCNAME: failed to get $number_of_joints joint modes" >&2; exit 1; fi 
+    if [[ -z "$mode" ]]; then echo "$name: $FUNCNAME: failed to get mode, check if status daemon is publishing on port $publisher_port" >&2; exit -1; fi
+    if [[ "$mode" != "$mode_no_power" ]]; then echo "$name: $FUNCNAME: expected the arm to be in mode $mode_no_power (no-power), got mode $mode" >&2; exit -1; fi
+    if [[ $( get 'arm/modes' | tr ',' '\n' | wc -l ) != $number_of_joints ]]; then echo "$name: $FUNCNAME: failed to get $number_of_joints joint modes" >&2; exit -1; fi 
     local -r timeout=${options_timeout}
     if [[ -n "$timeout" ]]; then
-        if (( $( echo "$timeout <= 0" | bc -l ) )); then echo "$name: $FUNCNAME: expected positive timeout, got $timeout" >&2; exit 1; fi
+        if (( $( echo "$timeout <= 0" | bc -l ) )); then echo "$name: $FUNCNAME: expected positive timeout, got $timeout" >&2; exit -1; fi
         local -r end_time=$( echo "`time_` + ($timeout)" | bc -l )
     fi
 
@@ -249,7 +249,7 @@ function initialise_joint
     local time=$( name-value-get --from json ${prefix}init/${joint_names[joint]}/time < $config )
     if [[ -z "$speed" && -z "$time" ]]; then speed=$default_init_speed; time=$default_init_time; fi
     if [[ ! ( -n "$speed" && -n "$time" ) ]]; then echo "$name: $FUNCNAME: expected both init speed and time for joint $joint (${joint_names[joint]})" >&2; exit -1; fi
-    if (( $( echo "$time <= 0" | bc -l ) )); then echo "$name: $FUNCNAME: expected positive time, got $time" >&2; exit 1; fi
+    if (( $( echo "$time <= 0" | bc -l ) )); then echo "$name: $FUNCNAME: expected positive time, got $time" >&2; exit -1; fi
     local key
     local -i status=0
     local -a speeds=( $zeros )
@@ -294,14 +294,14 @@ function init
     local -r mode_init=$( ur-arm-status --mode-from-name initialising )
     local -r joint_mode_init=$( ur-arm-status --joint-mode-from-name initialisation )
     local -r joint_mode_run=$( ur-arm-status --joint-mode-from-name running )
-    if [[ -z "$mode_init" ]]; then echo "$name: $FUNCNAME: init mode undefined, check if 'ur-arm-status --mode-from-name initialising' works" >&2; exit 1; fi
-    if [[ -z "$joint_mode_init" ]]; then echo "$name: $FUNCNAME: initialisation mode undefined, check if 'ur-arm-status --joint-mode-from-name initialisation' works" >&2; exit 1; fi
-    if [[ -z "$joint_mode_run" ]]; then echo "$name: $FUNCNAME: running mode undefined, check if 'ur-arm-status --joint-mode-from-name running' works" >&2; exit 1; fi
+    if [[ -z "$mode_init" ]]; then echo "$name: $FUNCNAME: init mode undefined, check if 'ur-arm-status --mode-from-name initialising' works" >&2; exit -1; fi
+    if [[ -z "$joint_mode_init" ]]; then echo "$name: $FUNCNAME: initialisation mode undefined, check if 'ur-arm-status --joint-mode-from-name initialisation' works" >&2; exit -1; fi
+    if [[ -z "$joint_mode_run" ]]; then echo "$name: $FUNCNAME: running mode undefined, check if 'ur-arm-status --joint-mode-from-name running' works" >&2; exit -1; fi
     local mode=$( get 'mode' )
-    if [[ "$mode" != "$mode_init" ]]; then echo "$name: $FUNCNAME: expected arm mode $init_mode, got $mode (try using operation 'restore')" >&2; exit 1; fi
+    if [[ "$mode" != "$mode_init" ]]; then echo "$name: $FUNCNAME: expected arm mode $init_mode, got $mode (try using operation 'restore')" >&2; exit -1; fi
     local -a joint_modes=( $( get 'arm/modes' | tr ',' ' ' ) )
-    if [[ -z "${joint_modes[@]}" ]]; then echo "$name: $FUNCNAME: failed to get joint modes, check if status daemon is publishing on port $publisher_port" >&2; exit 1; fi
-    if (( ${#joint_modes[@]} != number_of_joints )); then echo "$name: $FUNCNAME: failed to get $number_of_joints joint modes" >&2; exit 1; fi
+    if [[ -z "${joint_modes[@]}" ]]; then echo "$name: $FUNCNAME: failed to get joint modes, check if status daemon is publishing on port $publisher_port" >&2; exit -1; fi
+    if (( ${#joint_modes[@]} != number_of_joints )); then echo "$name: $FUNCNAME: failed to get $number_of_joints joint modes" >&2; exit -1; fi
     local -a init_config_values=()
     local -i init_status=0
     echo "initialising the arm at $( date +%X.%N )..." >&2
@@ -312,7 +312,7 @@ function init
             if [[ "${joint_modes[joint]}" == "$joint_mode_init" ]]; then 
                 echo -n "initialising joint $joint (${joint_names[joint]}) ... " >&2
                 initialise_joint $joint && echo " succeeded" >&2 || { echo " failed" >&2; init_status=1; }
-            else echo "$name: $FUNCNAME: expected joint $joint (${joint_names[joint]}) to be in mode $joint_mode_init (init), got ${joint_modes[joint]}" >&2; exit 1; fi
+            else echo "$name: $FUNCNAME: expected joint $joint (${joint_names[joint]}) to be in mode $joint_mode_init (init), got ${joint_modes[joint]}" >&2; exit -1; fi
         fi
     done
     if (( init_status == 0 )); then
@@ -326,21 +326,21 @@ function stow
 {
     local -r angles=$( name-value-get --from json ${prefix}stow/angles < $config )
     local -r speed=$( name-value-get --from json ${prefix}stow/speed < $config )
-    if [[ -z "$angles" ]]; then echo "$name: $FUNCNAME: ${prefix}stow/angles is not found in $config" >&2; exit 1; fi
-    if [[ -z "$speed" ]]; then echo "$name: $FUNCNAME: ${prefix}stow/speed is not found in $config" >&2; exit 1; fi
+    if [[ -z "$angles" ]]; then echo "$name: $FUNCNAME: ${prefix}stow/angles is not found in $config" >&2; exit -1; fi
+    if [[ -z "$speed" ]]; then echo "$name: $FUNCNAME: ${prefix}stow/speed is not found in $config" >&2; exit -1; fi
     send_command "movej([$angles],a=$default_acceleration,v=$speed)"
     wait_for_target "arm/angles" "$angles" $number_of_joints
 }
 
 function set_digital_out
 {
-    if [[ -z "$options_signal" ]]; then echo "$name: $FUNCNAME: option --signal is not given" >&2; exit 1; fi
+    if [[ -z "$options_signal" ]]; then echo "$name: $FUNCNAME: option --signal is not given" >&2; exit -1; fi
     IFS=,
     local -a signal=( $options_signal )
-    if (( ${#signal[@]} != 2 )); then echo "$name: $FUNCNAME: expected --signal=<id>,<on/off> but got $options_signal" >&2; exit 1; fi
+    if (( ${#signal[@]} != 2 )); then echo "$name: $FUNCNAME: expected --signal=<id>,<on/off> but got $options_signal" >&2; exit -1; fi
     local -i id=${signal[0]}
     local switch=$( echo ${signal[1]} | sed 's/on/True/' | sed 's/off/False/' )
-    if (( ! ( $switch == "True" || $switch == "False" ) )); then echo "$name: $FUNCNAME: expected the switch in --signal=<id>,<switch> to be 'on' or 'off', e.g. --signal=0,on but got ${signal[1]}" >&2; exit 1; fi
+    if (( ! ( $switch == "True" || $switch == "False" ) )); then echo "$name: $FUNCNAME: expected the switch in --signal=<id>,<switch> to be 'on' or 'off', e.g. --signal=0,on but got ${signal[1]}" >&2; exit -1; fi
     send_command "set_digital_out($id,$switch)"
 }
 
