control/applications/control-follow-waypoints-new: post-review brush up

diff --git a/control/applications/control-follow-waypoints-new b/control/applications/control-follow-waypoints-new
--- a/control/applications/control-follow-waypoints-new
+++ b/control/applications/control-follow-waypoints-new
@@ -8,7 +8,7 @@ function options_description
 --output-fields; show output fields (config is used if provided)
 --output-format; show output format of binary stream (config is used if provided)
 --sample-config; output sample config
---steering=[<steering>]; steering type (omni or skid); default: omni
+--steering=[<steering>]; steering type (omni or skid)
 EOF
 }
 
@@ -46,15 +46,15 @@ $( sample_config | sed 's/^/    /' )
               omni: wheels can rotate with respect to the body
               skid: wheels are fixed with respect to the body
     proximity: distance for deciding when a waypoint is reached
-    past-endpoint: 1 -> besides proximity condition, consider a waypoint as reached if the vehicle has moved past the end line, 0 -> use only proximity condition
+    past_endpoint: 1 -> besides proximity condition, consider a waypoint as reached if the vehicle has moved past the end line, 0 -> use only proximity condition
         ( the end line is a line which goes through the target waypoint and is perpendicular to the current wayline)
-    heading-is-absolute-default: 1 -> interpret heading_offset as the desired global (absolute) heading, 0 -> heading_offset is relative offset wrt the wayline heading
+    heading_is_absolute_default: 1 -> interpret heading_offset as the desired global (absolute) heading, 0 -> heading_offset is relative offset wrt the wayline heading
         ( this describes default behaviour when is_absolute is not provided in the input; when is_absolute is given, it takes precedence )
     frequency: control frequency, i.e. the rate at which wheel commands are output when moving towards a waypoint
         ( when the last given waypoint is reached, no output is produced until new waypoints are given )
     reset: 1 -> reset pid integral upon reaching every target waypoint, 0 -> no reset
     pid:
-        cross-track: p,i,d[,threshold] values, with optional integral threshold, for cross-track
+        cross_track: p,i,d[,threshold] values, with optional integral threshold, for cross-track
         heading: the same for heading
     waypoints:
         fields: csv fields of waypoints (required fields: $default_waypoints_fields_skid for skid steering and $default_waypoints_fields_omni for omni steering)
@@ -74,8 +74,8 @@ cat <<END
     "mode": "fixed",
     "steering": "omni",
     "proximity": "0.15",
-    "past-endpoint": 1,
-    "heading-is-absolute-default": 0,
+    "past_endpoint": 1,
+    "heading_is_absolute_default": 0,
     "frequency": "20.0",
     "reset": 0,
     "waypoints":
@@ -91,27 +91,27 @@ cat <<END
     },
     "pid":
     {
-        "cross-track": "0.3,0,0",
+        "cross_track": "0.3,0,0",
         "heading": "0.5,0,0"
     }
 }
 END
 }
 
-function import_config
+function config_fields_mandatory
 {
-    local config=$1
-    comma_path_value_to_var < <( name-value-convert --to path-value < "$config" ) || die "failed to import config '$config'"
-}
-
-function verify_that_required_parameters_are_set
-{
-    function die_if_config_does_not_have { local path=$1; [[ "${!path}" ]] || die "$path is not set"; }
-    local path
-    local exclude_paths_regex="(waypoints_binary|feedback_binary)"
-    for path in $( sample_config | name-value-convert | cut -d= -f1 | tr '/-' '_' | egrep -v "$exclude_paths_regex" ); do
-        die_if_config_does_not_have "$path"
-    done
+    cat <<END
+mode
+steering
+proximity
+past_endpoint
+heading_is_absolute_default
+frequency
+reset
+feedback/address
+pid/cross_track
+pid/heading
+END
 }
 
 function is_binary
@@ -125,28 +125,29 @@ function die { echo "$scriptname: $1" >&2; exit 1; }
 
 function prefix { csv-fields prefix --path $1; }
 
-function use_defaults_for_unset_parameters
+function set_default_waypoints_fields
 {
-    [[ "$feedback_fields" ]] || feedback_fields=$default_feedback_fields
-    [[ "$steering" ]] || steering=$default_steering
-    if [[ -z "$waypoints_fields" ]]; then 
-        case "$steering" in
-            omni) waypoints_fields=$default_waypoints_fields_omni ;;
-            skid) waypoints_fields=$default_waypoints_fields_skid ;;
-            *) die "steering '$steering' is not recongnised" ;;
-        esac
-    fi
+    local steering=$1
+    case "$steering" in
+        omni) waypoints_fields=$waypoints_fields_omni ;;
+        skid) waypoints_fields=$waypoints_fields_skid ;;
+        *) die "steering '$steering' is not recongnised" ;;
+    esac
 }
 
 
 scriptname=$( basename $0 )
 source $( which comma-application-util )
 
-default_feedback_fields="t,x,y,yaw"
-default_feedback_format="t,d,d,d"
-default_steering="omni"
-default_waypoints_fields_omni="x,y,heading_offset"
-default_waypoints_fields_skid="x,y"
+# default fields (note that default fields for waypoints depend on steering type and need to be set once the steering type is known)
+feedback_fields="t,x,y,yaw"
+waypoints_fields_omni="x,y,heading_offset"
+waypoints_fields_skid="x,y"
+
+feedback_binary=""
+waypoints_binary=""
+
+feedback_format="t,d,d,d"
 
 if (( $( comma_options_has --help "$@" ) || $( comma_options_has -h "$@" ) )); then
     (( $( comma_options_has --verbose "$@" ) || $( comma_options_has -v "$@" ) )) && verbose=1 || verbose=0
@@ -154,12 +155,18 @@ if (( $( comma_options_has --help "$@" ) || $( comma_options_has -h "$@" ) )); t
     exit
 fi
 
-comma_path_value_to_var < <( options_description | grep '^--config=' | comma-options-to-name-value "$@" )
-[[ -f "$config" ]] && import_config "$config"
-comma_path_value_to_var < <( options_description | comma-options-to-name-value "$@" )
-use_defaults_for_unset_parameters
-
 if (( $( comma_options_has --sample-config "$@" ) )); then sample_config; exit; fi
+
+eval $( options_description | grep '^--config=' | comma-options-to-name-value "$@" | comma_path_value_mangle )
+if [[ -f "$config" ]]; then
+    eval $( name-value-convert --to path-value < $config | comma_path_value_mangle; comma_status_ok ) || die "failed to import config '$config'"
+fi
+eval $( options_description | comma-options-to-name-value "$@" | comma_path_value_mangle )
+if [[ -z "$waypoints_fields" ]]; then
+    [[ "$steering" ]] || die "failed to set default waypoints/fields; steering type is required"
+    set_default_waypoints_fields $steering
+fi
+
 if (( $( comma_options_has --input-fields "$@" ) )); then echo $waypoints_fields; exit; fi
 
 error_fields=$( control-error --output-fields )
@@ -173,14 +180,14 @@ if (( $( comma_options_has --output-fields "$@" ) )); then
     exit
 fi
 if (( $( comma_options_has --output-format "$@" ) )); then
-    echo ${feedback_binary:-$default_feedback_format},$error_binary,$command_binary
+    echo ${feedback_binary:-$feedback_format},$error_binary,$command_binary
     exit
 fi
 
 passed_fields=$( prefix target <<< $waypoints_fields ),$( prefix feedback <<< $feedback_fields ),$error_fields
 is_binary && passed_binary=$waypoints_binary,$feedback_binary,$error_binary || passed_binary=
 
-verify_that_required_parameters_are_set
+config_fields_mandatory | comma_path_assert_defined || die "found undefined config parameters"
 
 control-error \
         --fields=$waypoints_fields \
