control/applications/control-follow-waypoints-new: minor refactoring and changes in the interface

diff --git a/control/applications/control-follow-waypoints-new b/control/applications/control-follow-waypoints-new
--- a/control/applications/control-follow-waypoints-new
+++ b/control/applications/control-follow-waypoints-new
@@ -1,24 +1,40 @@
 #!/bin/bash
 
-function option_description
+function options_description
 {
     cat <<EOF
 --config=[<config>]; config file name
---output-fields; show output fields and exit
---output-format; show output format and exit
---sample-config; output sample config and exit
+--input-fields; show waypoint fields (config is used if provided)
+--output-fields; show output fields (config is used if provided)
+--output-format; show output format of binary stream (config is used if provided)
+--sample-config; output sample config
+--steering=[<steering>]; steering type (omni or skid); default: omni
 EOF
 }
 
 function usage
 {
-    cat << END
+    cat <<END
 
     take waypoints on stdin and output wheel commands based on the position feedback to stdout
 
 options:
-$( option_description | sed 's/^/    /g' )
+$( options_description | sed 's/^/    /g' )
 
+notes:
+    - command line options take precedence over config
+    - output is binary if both waypoints and feedback are binary
+
+examples:
+    cat waypoints.csv | $scriptname --config=config.json > commands.csv
+    $scriptname --input-fields --steering=omni
+    $scriptname --output-fields --steering=omni
+    $scriptname --output-format --steering=omni
+    $scriptname --sample-config
+
+END
+    if (( ! $verbose )); then echo "for more output: $scriptname -h -v" >&2; return; fi
+    cat <<END
 example config file:
     
 $( sample_config | sed 's/^/    /' )
@@ -26,7 +42,9 @@ $( sample_config | sed 's/^/    /' )
     mode: waypoint following mode, fixed or dynamic
           fixed: wait until the current waypoint reached, then go to the next waypoint
           dynamic: if a new waypoint received, while the current waypoint is not reached, go to the new waypoint straightaway
-    steering: steering mode (omni or skid)
+    steering: steering type, omni or skid
+              omni: wheels can rotate with respect to the body
+              skid: wheels are fixed with respect to the body
     proximity: distance for deciding when a waypoint is reached
     past-endpoint: 1 -> besides proximity condition, consider a waypoint as reached if the vehicle has moved past the end line, 0 -> use only proximity condition
         ( the end line is a line which goes through the target waypoint and is perpendicular to the current wayline)
@@ -40,20 +58,14 @@ $( sample_config | sed 's/^/    /' )
         heading: the same for heading
     waypoints:
         address: generic address for the source of target waypoints (if no adress is given, stdin is used)
-        fields: csv fields of waypoints (required fields: 'x,y' for skid and 'x,y,heading_offset' for omni steering)
-        binary: binary format of waypoints
+        fields: csv fields of waypoints (required fields: $default_waypoints_fields_skid for skid steering and $default_waypoints_fields_omni for omni steering)
+        binary: binary format of waypoints (ascii stream is assumed by default)
     feedback:
         address: generic address for feedback
-        fields: csv fields of feedback (required fields: 't,x,y,yaw')
-        binary: binary format of feedback
-
-examples:
-        $scriptname --config=config.json
-        $scriptname --output-fields --config=config.json
-        $scriptname --output-format --config=config.json
+        fields: csv fields of feedback (required fields: $default_feedback_fields)
+        binary: binary format of feedback (ascii stream is assumed by default)
 
 END
-    exit
 }
 
 function sample_config
@@ -88,51 +100,71 @@ cat <<END
 END
 }
 
-function die { echo "$scriptname: $1" >&2; exit 1; }
-
 function import_config
 {
     local config=$1
-    waypoints_address=
-    comma_path_value_to_var < <( name-value-convert --to path-value < "$config" )
-    [[ "$config" ]] || die "config file is not given"
-    [[ -f "$config" ]] || die "config file '$config' is not found"
-    function die_if_config_does_not_have { local path=$1; [[ "${!path}" ]] || die "$path not found in '$config'"; }
-    local path
-    for path in mode \
-                steering \
-                proximity \
-                past_endpoint \
-                heading_is_absolute_default \
-                frequency \
-                reset \
-                feedback_address \
-                feedback_fields \
-                pid_cross_track \
-                pid_heading \
-                waypoints_fields; do
-        die_if_config_does_not_have "$path"
-    done
-    if [[ -z "$waypoints_binary" && -z "$feedback_binary" ]]; then binary_output=0
-    elif [[ -n "$waypoints_binary" && -n "$feedback_binary" ]]; then binary_output=1
-    else die "input and feedback streams should be both ascii or both binary"; fi
+    comma_path_value_to_var < <( name-value-convert --to path-value < "$config" ) || die "failed to import config '$config'"
 }
 
+function verify_that_required_parameters_are_set
+{
+    function die_if_config_does_not_have { local path=$1; [[ "${!path}" ]] || die "$path is not set"; }
+    local path
+    local exclude_paths_regex="(waypoints_binary|feedback_binary)"
+    for path in $( sample_config | name-value-convert | cut -d= -f1 | tr '/-' '_' | egrep -v "$exclude_paths_regex" ); do
+        die_if_config_does_not_have "$path"
+    done
+}
+
+function is_binary
+{
+    [[ -z "$waypoints_binary" && -z "$feedback_binary" ]] && return 1
+    [[ -n "$waypoints_binary" && -n "$feedback_binary" ]] && return 0
+    die "input and feedback streams should be both ascii or both binary"
+}
+
+function die { echo "$scriptname: $1" >&2; exit 1; }
+
 function prefix { csv-fields prefix --path $1; }
+
+function use_defaults_for_unset_parameters
+{
+    [[ "$feedback_fields" ]] || feedback_fields=$default_feedback_fields
+    [[ "$waypoints_address" ]] || waypoints_address="-"
+    [[ "$steering" ]] || steering=$default_steering
+    if [[ -z "$waypoints_fields" ]]; then 
+        case "$steering" in
+            omni) waypoints_fields=$default_waypoints_fields_omni ;;
+            skid) waypoints_fields=$default_waypoints_fields_skid ;;
+            *) die "steering '$steering' is not recongnised" ;;
+        esac
+    fi
+}
 
 
 scriptname=$( basename $0 )
 source $( which comma-application-util )
 
-if (( $( comma_options_has --help "$@" ) || $( comma_options_has -h "$@" ) )); then usage; fi
-comma_path_value_to_var < <( option_description | comma-options-to-name-value "$@" )
+default_feedback_fields="t,x,y,yaw"
+default_feedback_format="t,d,d,d"
+default_steering="omni"
+default_waypoints_fields_omni="x,y,heading_offset"
+default_waypoints_fields_skid="x,y"
+default_waypoints_address="-"
 
-if (( $( comma_options_has --sample-config "$@" ) )); then
-    sample_config
+if (( $( comma_options_has --help "$@" ) || $( comma_options_has -h "$@" ) )); then
+    (( $( comma_options_has --verbose "$@" ) || $( comma_options_has -v "$@" ) )) && verbose=1 || verbose=0
+    usage $verbose
     exit
 fi
 
-import_config "$config"
+comma_path_value_to_var < <( options_description | grep '^--config=' | comma-options-to-name-value "$@" )
+[[ -f "$config" ]] && import_config "$config"
+comma_path_value_to_var < <( options_description | comma-options-to-name-value "$@" )
+use_defaults_for_unset_parameters
+
+if (( $( comma_options_has --sample-config "$@" ) )); then sample_config; exit; fi
+if (( $( comma_options_has --input-fields "$@" ) )); then echo $waypoints_fields; exit; fi
 
 error_fields=$( control-error --output-fields )
 error_binary=$( control-error --output-format )
@@ -140,20 +172,19 @@ error_binary=$( control-error --output-format )
 command_fields=$( control-command --steering=$steering --output-fields )
 command_binary=$( control-command --steering=$steering --output-format )
 
-passed_fields=$( prefix target <<< $waypoints_fields ),$( prefix feedback <<< $feedback_fields ),$error_fields
-output_fields=$passed_fields,$( prefix command <<< $command_fields )
-if (( $( comma_options_has --output-fields "$@" ) )); then echo $output_fields; exit; fi
-
-passed_binary=
-(( binary_output )) && passed_binary=$waypoints_binary,$feedback_binary,$error_binary
-
+if (( $( comma_options_has --output-fields "$@" ) )); then
+    echo $( prefix feedback <<< $feedback_fields ),$error_fields,$( prefix command <<< $command_fields )
+    exit
+fi
 if (( $( comma_options_has --output-format "$@" ) )); then
-    (( binary_output )) || die "failed to get output format since output is ascii"
-    echo $passed_binary,$command_binary
+    echo ${feedback_binary:-$default_feedback_format},$error_binary,$command_binary
     exit
 fi
 
-default_waypoints_address="-"
+passed_fields=$( prefix target <<< $waypoints_fields ),$( prefix feedback <<< $feedback_fields ),$error_fields
+is_binary && passed_binary=$waypoints_binary,$feedback_binary,$error_binary || passed_binary=
+
+verify_that_required_parameters_are_set
 
 io-cat ${waypoints_address:-$default_waypoints_address} \
     | control-error \
