control-follow-waypoints dont check for files so that we can pass temporary files

diff --git a/control/applications/control-follow-waypoints b/control/applications/control-follow-waypoints
--- a/control/applications/control-follow-waypoints
+++ b/control/applications/control-follow-waypoints
@@ -157,9 +157,7 @@ fi
 if (( $( comma_options_has --sample-config "$@" ) )); then sample_config; exit; fi
 
 eval $( options_description | grep '^--config=' | comma-options-to-name-value "$@" | comma_path_value_mangle )
-if [[ -f "$config" ]]; then
-    eval $( name-value-convert --to path-value < $config | comma_path_value_mangle; comma_status_ok ) || die "failed to import config '$config'"
-fi
+eval $( name-value-convert --from=json < "$config" | comma_path_value_mangle; comma_status_ok ) || die "failed to import config '$config'"
 eval $( options_description | comma-options-to-name-value "$@" | comma_path_value_mangle )
 if [[ -z "$waypoints_fields" ]]; then
     [[ "$steering" ]] || die "failed to set default waypoints/fields; steering type is required"
